name: neovim

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - master

jobs:
  vint:
    name: Run vint as a linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: vint
        uses: reviewdog/action-vint@v1
        with:
          github_token: ${{ secrets.github_token }}
          level: error
          reporter: github-pr-review

  vim-themis:
    name: Run themis tests

    strategy:
      matrix:
        nvim_version:
          - nightly
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest # Currently, out-of-date to build neovim.

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install vim-themis
        uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis

      - name: Install neovim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: ${{ matrix.nvim_version }}

      - name: Run themis tests
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: |
          ./vim-themis/bin/themis ./test
